### ISSUE TITLE
SQLite: Could not create connection to database server

### ISSUE THREAD

**Issue by AlexanderMandera** [erikzimmermann/TradeSystem#486]
**Describe the bug**
![image](https://github.com/erikzimmermann/TradeSystem/assets/3356015/660fb2b4-a67b-4782-ae4a-44596e7d6e46)
It shows this error even if you use the SQLite database type.

File `tradelog.db` was created and is available in the `plugins/TradeSystem` folder

**To Reproduce**
Config.yml entry:
```yaml
  Database:
    # Values: SQLite, MySQL
    Type: SQLite
    MySQL:
      Connection_URL: jdbc:mysql://localhost:3306/tradelog?autoReconnect=true&useSSL=false
      User: root
      Password: password
```

**Expected behavior**
Uses the database without any errors

**Screenshots**
See above

**Additional context**
Related Discord Message: https://discord.com/channels/578230584871092235/585916390083526796/1149754285379309660

**Discord contact**: kaludi (reported on Support Discord)
